export function getTuningDom() {
  return {
    tuningPage: document.getElementById("tuningPage"),

    awayName: document.getElementById("awayName"),
    homeName: document.getElementById("homeName"),
    awayPitcher: document.getElementById("awayPitcher"),
    homePitcher: document.getElementById("homePitcher"),
    awayScore: document.getElementById("awayScore"),
    homeScore: document.getElementById("homeScore"),
    broadcastInning: document.getElementById("broadcastInning"),
    broadcastStatus: document.getElementById("broadcastStatus"),
    inningText: document.getElementById("inningText"),
    outsText: document.getElementById("outsText"),
    countText: document.getElementById("countText"),
    basesText: document.getElementById("basesText"),
    currentBatterText: document.getElementById("currentBatterText"),
    currentPitcherText: document.getElementById("currentPitcherText"),
    firstRunnerText: document.getElementById("firstRunnerText"),
    secondRunnerText: document.getElementById("secondRunnerText"),
    thirdRunnerText: document.getElementById("thirdRunnerText"),
    headerBase1: document.getElementById("headerBase1"),
    headerBase2: document.getElementById("headerBase2"),
    headerBase3: document.getElementById("headerBase3"),
    ballLights: document.getElementById("ballLights"),
    strikeLights: document.getElementById("strikeLights"),
    outLights: document.getElementById("outLights"),
    zoneGrid: document.getElementById("zoneGrid"),
    zoneText: document.getElementById("zoneText"),
    lineupBody: document.getElementById("lineupBody"),
    log: document.getElementById("log"),

    newGameBtn: document.getElementById("newGameBtn"),
    stepPitchBtn: document.getElementById("stepPitchBtn"),
    stepPaBtn: document.getElementById("stepPaBtn"),
    halfInningBtn: document.getElementById("halfInningBtn"),
    playGameBtn: document.getElementById("playGameBtn"),
    sim10Btn: document.getElementById("sim10Btn"),
    sim162Btn: document.getElementById("sim162Btn"),
    resetTuningRosterBtn: document.getElementById("resetTuningRosterBtn"),

    tuningCurrentScore: document.getElementById("tuningCurrentScore"),
    tuningCurrentState: document.getElementById("tuningCurrentState"),
    tuningGameSummaryTable: document.getElementById("tuningGameSummaryTable"),
    tuningAwayPlayerStatsTable: document.getElementById("tuningAwayPlayerStatsTable"),
    tuningHomePlayerStatsTable: document.getElementById("tuningHomePlayerStatsTable"),
    tuningAwayQoCTable: document.getElementById("tuningAwayQoCTable"),
    tuningHomeQoCTable: document.getElementById("tuningHomeQoCTable"),
    tuningSeasonHeadline: document.getElementById("tuningSeasonHeadline"),
    tuningSeasonGamesValue: document.getElementById("tuningSeasonGamesValue"),
    tuningSeasonRecordValue: document.getElementById("tuningSeasonRecordValue"),
    tuningSeasonSummaryTable: document.getElementById("tuningSeasonSummaryTable"),
    tuningSeasonAwayQoCTable: document.getElementById("tuningSeasonAwayQoCTable"),
    tuningSeasonHomeQoCTable: document.getElementById("tuningSeasonHomeQoCTable"),
    tuningSeasonAwayPlayerStatsTable: document.getElementById("tuningSeasonAwayPlayerStatsTable"),
    tuningSeasonHomePlayerStatsTable: document.getElementById("tuningSeasonHomePlayerStatsTable"),

    editorSideSelect: document.getElementById("editorSideSelect"),
    editorPlayerTypeSelect: document.getElementById("editorPlayerTypeSelect"),
    editorSlotSelect: document.getElementById("editorSlotSelect"),
    editorNameInput: document.getElementById("editorNameInput"),
    editorContactInput: document.getElementById("editorContactInput"),
    editorPowerInput: document.getElementById("editorPowerInput"),
    editorEyeInput: document.getElementById("editorEyeInput"),
    editorControlInput: document.getElementById("editorControlInput"),
    editorStuffInput: document.getElementById("editorStuffInput"),
    applyPlayerEditBtn: document.getElementById("applyPlayerEditBtn"),
    reloadEditorBtn: document.getElementById("reloadEditorBtn"),
  };
}